site_name: My Docs
site_url: https://piyushn88.github.io/documents
nav:
    - Home: index.md
    - Git: git.md
    - Git_Commands: git_commands.md
    - Minikube: minikube.md
    - Airflow: airflow.md
theme: readthedocs